os: unstable

environment:
  matrix:
    - builder: cygwin
      platform: Win32
      
    - builder: cygwin 
      platform: x64
branches:
  only:
    - master

#notifications:
#  - provider: Email
#    on_build_success: false
#    on_build_failure: false
#    on_build_status_changed: false

before_build:
  - cmd: ECHO this is batch  %APPVEYOR_ACCOUNT_NAME%
  - ls -l
  - uname -a
  - where bash  


platform: x86
#build:
#  - PS: Exit- AppVeyorBuild
  
install:
#  - appveyor DownloadFile https://cygwin.com/setup-x86.exe -FileName C:\cygwin\setup-x86.exe
#  - C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P mingw64-i686-gcc-g++ -P mingw64-x86_64-gcc-g++  -P autotools -P autoconf -P autoreconf -P automake -P bison -P libtool -P make -P gettext-devel -P intltool -P libiconv -P pkg-config 
  - if "%builder%"=="cygwin" ( if "%platform%"=="Win32" ( C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"   ( C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel  -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="Win32" ( set "PATH=C:\cygwin\bin;%PATH%" ; set "TRAVIS_OS_NAME=Win32" ))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"   ( set "PATH=C:\cygwin64\bin;%PATH%" ; set "TRAVIS_OS_NAME=x64"  ))
  - cmd: ECHO %PATH% 


build_script:
  - perl -version
  - cd ./bng2/Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate
  - bash .dist_windows.sh %platform%
  
  
artifacts:
  - path: BioNetGen-2.3.0-Win32.zip
    name: BioNetGen
  
deploy:
  - provider: FTP
  - protocol: ftp
  - skip_cleanup: true
  - host: ftp.midcapsignals.com/midcap/d_appveyor
  - username: roberthclark
  - password:
      - secure: K22E4pSAup6/htlGmoSBMw==  
  
