environment:
  CTEST_OUTPUT_ON_FAILURE: 1


install:
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"		
  - C:\msys64\usr\bin\bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain   libtool make patch mingw-w64-x86_64-libtool"
  - choco install -y strawberryperl
  - "SET PATH=C:\\strawberry\\perl\\bin;C:\\strawberry\\perl\\site\\bin;%PATH%"
  - set PATH=C:\msys64\usr\bin;%PATH%

branches:
  # whitelist
  only:
    - master
    - release
platform: x64


build_script:
  - cmd: echo Running cmake ...
  - cd ./bng2/Network3 
  - mkdir -p m4 
  - cd .. 
#  - C:\msys64\usr\bin\bash -lc "perl $(cygpath ${APPVEYOR_BUILD_FOLDER})/bng2/make_dist.pl --build --validate"

# artifacts:
#  - path: build\NFsim.exe
#    name: NFsim

# notifications:
#   - provider: Slack
#     auth_token:
#       secure: jN4Fas2b8/Z1yNInrC6yWZf1sHzA5M7M/wANf+O4nRQLRqNqLsmNFGMNusaS+adFyS0kz3TfGBtLjAEKeh84jw==
#     channel: build-results

# deploy:

#     # Amazon S3 deployment provider settings
#   - provider: S3
#     access_key_id:
#       secure: gyxTxeHww7ldSGxRSqjkAA1qa2JodkLDtmZeVrdmPfA=
#     secret_access_key:
#       secure: qbD+jQk8IRRrHhucUlL6D17o4DffrAObRzBlo1ll8NzHG09o2kCGskQzd828WLJD
#     bucket: bionetgen
#     folder: 1.12
#     on:
#       branch: release 
#     artifact: nfsim
#     set_public: true
