os:
  - osx
  - linux

language: c++
sudo: false

deploy:
  skip_cleanup: true

notifications:
  slack: faederlab:l0waIGp58v8ZV74N7QmXGoWs
   
script:
  - cd ./bng2/Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate
  
  
