os:
  - osx
#  - linux

language: c++
sudo: false

env:
  global:
    - secure: "Kda7YvWhefM1q8lK4bNvm7szNJD3Z0VEGYMWIT7lHv7P18jnYu/o+5zrhX3mt5vNffsK/Vhr4rPncw/MJQdRNME3XwYcP06xzHUdrwsUbg6zy4CmTITMgWkO0FTGPX7oJjSMpRUCC7uFBV74LjiLgw7PSyGlbJyPog76tiketNQTbMIfals49syErP+TfvM2UtxqjhvMG5MO73syt3pJ/63uV1j+ke4jY9l4x1U8w3XS9c6IsvDv+J0aHBNehvU6TDlkaC9EDJ4K7HJs4OkrtN1A2pmLiOGKaRncAeRs/Ptj9sk2kLEe6g9GAFe+woD4YrAxyCw69gDCpRRTiSpk+VO+MvCKdA4bu4snK4McXm+SqnYqEhbcSc0d/orlsGFJMOP8zFp1hKYDZTJbpxSW6TFyg/3nfRQfK1wj0Bwnrg6A+S6tIRXZPKlTaj+RqLqucLw2WinPR0s1jP7zi2cvh1ZWsiCSjpP8RdJ41WMKmGRFtHH5DPkJZa6KYWVpZqZsMYYxiKVLGlIFoPmNs/LIGGi00nsgZRSQmlTeyRWxV7+fCuj5SlkOIFh7O0kfxku7merL8FUoqH+Pl0wyvRiDP9gj0lvjeirvI1bwGKtPNyn5MAjpf4NMBg/sjdT12uPz8XUrNZZGYV/XuHXd/U/4B3StGMWapWMjnuPLjLsVbhs="
    - secure: "hm1QdjgMrjPhaYTaCVb/dkSPTTFzF0RAMs3a6EQAtvYMZCoJbyxZtzkvQ5oYO3ez5j2rbXaxDEQ/mWMn/DMx3hwvPR7Fu+w1KqIL4FlbS5PZO4Bs7Jo+lMU2f6Wl2O99aGUJ8NAoowTWgg0kgss0U5HfvK4++3S6Oh7x58OWjM7uynqVe8/hzvkLOyWfFITWXkPZwgOcyaZX5E+H/uYcQjmaGYr4TV3CLn3lB3IhBYSb+Apo39gXwB0K5yWXpLIEuINxsTveVVMeEunSII4HpNT/C67+fduGhWBy4d4lYjBTLiuS7mAyfoeJK9lIsVd3H5MKRIHRw0ORKUDPEmak0mmFCGOm0W5LALgyiaSSkKt6T/NDPn4coFDwh8pRT149NNZOto0A830DfcuR8mh4ZbyI9kYGnJVrhM2fhNNGmtsdcnBxi0UzZmmGl+YchaBdb3wS+j7SX+uSvxT9aUD1W8XZ+Whpubpf8YwYBLEPxtOcY596+4enu4fEVtSqJpOcRqQzyS2FP8k5mFaRblLd230RbTkR99TrGxHVVdeOGirpUCIpowlnt56DXMmfD3R7s797RZYTJx1elZBMGbaxruzIwhsEDBOWgOfO8GXuXcrua7xjzb8ChcliWtp3crdxUtZ4T6lc77/VstatafP2YnhBXr9+yUPnJyzJ/jzrAK4="

#notifications:
#  slack: faederlab:l0waIGp58v8ZV74N7QmXGoWs
   
script:
  - cd ./bng2/Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate
  
after_success:
  - "curl -T ./VERSION  -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/junk/"


#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: bionetgen-travis-rhclark
#  skip_cleanup: true  
