os:
  - linux
env:  
  - PLATFORM_ENV=Linux
#  - osx
  
language: c++
sudo: false

env:
  global:
    - secure: "ifMdh+XG3tYjLP65ASs9REcCBCLIaYCRda3pDbuoGACEpyqaEyTAbu5D/kVRZS58gUOOGDqZEgeA0qghbWAV1suEVfrkXTkJHkG7B+4kAUDmaeo210oMYBKM+KcMxsYNSU2uemn8QDdxbHj0z51OZmzkmEUiLmSxovETn5XAf5OlaPmn67MujC/ZxKrrpwhOSZjx/gzXkrsWnx1MJxH484EjJEClpBLSExy6mrEDXMflOt6PivJpmCenwTsZkIw3GqK0OYT8D2rY4RxzvSkXQqHCrjDQbHKerrSVFdaK9KrDo1Gs/QlGnFlPmaROudd/lYH/JDSloha8K/4t1wzXP+zAgKKFOVDl6E1STPlUlkRFY7JyCRkr38Zxw3078KyZKH1Qpqh2whQwUXUD7Ao346X39hV5IOLTeATYA39JcIVjDoHIGlwvr6RwDBmCfWq8dtupOCakWeHiBjfKFt5uAtF6tVpp04PodtCeCKZ+/i0Zpmwejh/WTMwxmwsox+gUwL++Yx+DEycb8dfPMQqfncEcgMV5iaCuL0ZqndqxywPyocXHnIMxwJxNUutTgpyPSAQB1DWDNgg7UsatNZVkoH/uzwuQJ4JPKf2COPGdr2fST3/PYVpMJXTtmCd7Os3AG3KkB49DdKso7e/DRLcZ77KgUmAxMA/q2gLrY1Ts9O0="
    - secure: "fpYWuT8BKkZpFjNzq2Jm1XWnZUV/rdOY+FBtIe8jlQnSobhcHODNGWgHYXKxInWAyMx0sBXh4FxWU0xWl5pdSsp15s5ObnDgAFaQVOCEFNxnY49pCcgTP2Gas3Qugbk/sr/edvwK98AijrITyuxu5Mz8NZzCE4EzbJvTloPhS8UetenzSn+SED5jjyOc7xH1RmW9gukmI5DCIVvAZMV3Lr3/m4EobX/WzO2IAi8Gm5e3Cy9HdkQg3uh827t1oMmhwdilbAsithvRRpBKyyHxfYA28j6fVldZqr2HZTlpj0dRHAKL+0UZsp4KmhG+GT+Ct49+NlY368YyqItRYi4A0Iou1zOiukZKgPqMXACyOzXiEPul6stftGSLcLsuGib+QORX0nkEMGx9aSESesn6xeoCluUpWL7H3/GecB2kFrGRMdJlieZOS/s9rP4aJIyONCKfAfEp7lOLFnO7m5yrY+gJciiSOZxLPdLBm8+9B3fuOOEVn3TyN0E2fX7DVmwM+Fki05bMssdz8/MejcGXWj9g+CXjAtsnprtf+3PTDmNwKYXX4WBi918wk0/sQB7Qoy0HtlIltbxrh7kYsEQaA7922POaGtLWA8t/oFuGwUGmkgqsw2tG86eNieW4mXKULx8hb7DOZvwsIGStzmvaOU7lsCKMPbhfpGx1G6Q3l0I="


notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)  %{result} in %{duration}"
       - "Author: %{author}   Repository@Branch: %{repository}@%{branch}"
       - "Distribution Package:  http://www.midcapsignals.com/midcap/junk/spag.html"
       - "Build details:  %{build_url} "
   
script:
  - cd ./bng2/Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate --archive --overwrite


after_success:
  - source dist_package.sh 
#  - "curl -T ./VERSION  -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/junk/"


#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: bionetgen-travis-rhclark
#  skip_cleanup: true  
